version: '2'
#services:
#  nodemochachaitutorial_node-mocha-chai-tutorial_1:
#    build: .  

services:
  nodemochachaitutorial_node-mocha-chai-tutorial_1:
    build: .

  mongo:
    extends:
      file: common.yml
      service: mongo