version: '2'
#services:
#  nodemochachaitutorial_node-mocha-chai-tutorial_1:
#    build: .  

services:
  nodemochachaitutorial_node-mocha-chai-tutorial_1:
    build: .
    links:
      - db
    restart: always

  db:
    image: mongo:latest
    ports:
      - "27017:27017"